CREATE SEQUENCE seq_endereco
start with 1
Increment by 1 ;

--Bairro 1
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 2.
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 3
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 4
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 5
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 6
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 7
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 8
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 9
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 10
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 11
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 12
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 13
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 14
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 15
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 16
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 17
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 18
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 19
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 20
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 21
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 22
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 23
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 24
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 25
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 26
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 27
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 28
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 29
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 30
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 31
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 32
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 33
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 34
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 35
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 36
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 37
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 38
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 39
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 40
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 41
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 42
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 43
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 44
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 45
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 46
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 47
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 48
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 49
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 50
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 51
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 52
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 53
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 54
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 55
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 56
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 57
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 58
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 59
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 60
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 61
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 62
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 63
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 64
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 65
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 66
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 67
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 68
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 69
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 70
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 71
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 72
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 73
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 74
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 75
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 76
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 77
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 78
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 79
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 80
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 81
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 82
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 83
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 84
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 85
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 86
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 87
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 88
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 89
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 90
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 91
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 92
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 93
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 94
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 95
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 96
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 97
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 98
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 99
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 100
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 101
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 102.
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 103
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 104
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 105
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 106
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 107
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 108
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 109
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 110
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 111
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 112
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 113
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 114
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 115
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 116
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 117
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 118
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 119
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 120
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 121
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 122
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 123
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 124
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 125
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 126
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 127
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 128
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 129
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
--Bairro 130
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13564630,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,13566581,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');
INSERT INTO T_SAK_ENDERECO (CD_END_CORREIO,CD_BAIRRO,NR_CEP,DS_LOGRADOURO) VALUES (seq_endereco.nextval,1,,'Centro');

