ALTER TABLE T_SLV_CATEGORIA RENAME COLUMN 
ds_sigla_categoria TO ds_sigla_categ;

ALTER TABLE T_SLV_CATEGORIA DROP CONSTRAINT 
un_slv_categoria_desc;

ALTER TABLE T_SLV_CATEGORIA
ADD CONSTRAINT UN_SLV_CATEG_DESC UNIQUE(ds_categoria);

ALTER TABLE T_SLV_AUTOR MODIFY
nm_segundo_autor varchar2(30);

ALTER TABLE T_SLV_AUTOR ADD
ds_email varchar2(40) not null;

ALTER TABLE T_SLV_AUTOR MODIFY
ds_email varchar2(60) null;

ALTER TABLE T_SLV_AUTOR_LIVRO MODIFY
nr_isbn number(13);

ALTER TABLE T_SLV_LIVRO MODIFY
nr_isbn number(13);

ALTER TABLE T_SLV_AUTOR ADD
nm_pais_origem varchar2(30) null;

ALTER TABLE T_SLV_LIVRO 
ADD CONSTRAINT UN_SLV_LIVRO_TITULO UNIQUE(nm_titulo);

ALTER TABLE T_SLV_AUTOR_LIVRO 
DROP CONSTRAINT FK_SLV_AUTOR_LIVRO_AUTOR;

ALTER TABLE T_SLV_LIVRO 
DROP CONSTRAINT PK_SLV_LIVRO CASCADE;

ALTER TABLE T_SLV_CATEGORIA 
DISABLE CONSTRAINT UN_SLV_CATEGORIA_SIGLA;