CREATE SEQUENCE seq_estado
As int
start with 1
Increment by 1 ;


INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'ACRE','AC');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'ALAGOAS','AL');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'AMAPÁ','AP');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'AMAZONAS','AM');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'BAHIA','BA');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'CEARÁ','CE');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'ESPÍRITO SANTO','ES');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'GOIÁS','GO');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'MARANHÃO','MA');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'MATO GROSSO','MT');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'MATO GROSSO DO SUL','MS');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'MINAS GERAIS','MG');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'PARÁ','PA');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'PARAÍBA','PB');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'PARANÁ','PR');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'PERNAMBUCO','PE');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'PIAUÍ','PI');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'RIO DE JANEIRO','RJ');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'RIO GRANDE DO NORTE','RN');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'RIO GRANDE DO SUL','RS');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'RONDÔNIA','RO');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'RORAIMA','RR');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'SANTA CATARINA','SC');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'SÃO PAULO','SP');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'SERGIPE','SE');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (seq_estado.nextval,'TOCANTINS','TO');
