INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,43,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,43,'Coronel Negreiros');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,43,'Maresia');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,44,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,44,'Cristo Rei');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,44,'São Sebastião');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,45,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,45,'Vista Alegre');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,45,'Taquarinha');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,46,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,46,'Terra Firme');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,46,'Ayrton Senna');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,47,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,47,'Acajatuba');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,47,'Cacau Pireira');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,48,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,48,'Nossa Senhora Aparecida');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,48,'Santo Antônio');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,49,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,49,'Fortaleza');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,49,'Macaxeiral');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,50,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,50,'Calçada');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,50,'Resgate');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,51,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,51,'Aviário');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,51,'Aeroporto');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,52,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,52,'Alto Maron');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,52,'Cruzeiro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,53,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,53,'Bomba');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,53,'Dois de Julho');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,54,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,54,'Agemiro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,54,'Quide');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,55,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,55,'Daniel Gomes');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,55,'Fátima');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,56,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,56,'Miragem');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,56,'Realengo');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,57,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,57,'Ceará');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,57,'Amparo');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,58,'Cidade Nova');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,58,'Kennedy');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,58,'Jequiezinho');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,59,'Kaikan');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,59,'Vila Verde');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,59,'Liberdade I');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,60,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,60,'Siqueira');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,60,'Floresta');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,61,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,61,'Açude');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,61,'Capuã');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,62,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,62,'João Cabral');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,62,'Frei Damião');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,63,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,63,'Acaracuzinho');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,63,'Cágado');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,64,'Bonfim');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,64,'Bilheira');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,64,'Aprazível');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,65,'Deserto');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,65,'Praia da Baleia');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,65,'Violete');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,66,'Gavião');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,66,'Aldeoma');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,66,'Alto Alegre');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,67,'Bastiana');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,67,'Cohab');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,67,'Areias II');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,68,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,68,'Herval');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,68,'São João');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,69,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,69,'Lameiro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,69,'Muriti');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,70,'Santo Antônio');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,70,'Jucutuquara');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,70,'Maruípe');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,71,'23 Maio');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,71,'Horto');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,71,'Olaria');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,72,'Modelo');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,72,'Morada Feliz');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,72,'Vila Oásis');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,73,'Aquidaban');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,73,'Coramara');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,73,'Paraíso');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,74,'Regência');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,74,'Nova Betânia');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,74,'Rio Quartel');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,75,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,75,'Inocoop');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,75,'Forno Velho');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,76,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,76,'Boa Vista');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,76,'Camurugi');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,77,'Barbados');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,77,'Baunilha');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,77,'Bela Vista');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,78,'Vila Rica');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,78,'Jequitibá');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,78,'Guaraná');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,79,'Jucu');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,79,'Guaritas');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,79,'Tabajara');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,80,'Asa Branca');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,80,'Jardim Guanabara');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,80,'Guarema');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,81,'Lourdes');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,81,'Niquelândia');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,81,'Acamp Macedo');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,82,'Carrijo');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,82,'Cruvinel');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,82,'Naves Martins');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,83,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,83,'Vila Joice');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,83,'Povoado Planalto Verde');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,84,'Anhanguera');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,84,'Eldorado');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,84,'Gameleiras');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,85,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,85,'Maria Xavier Caiado');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,85,'Rodoviário');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,86,'Centro');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,86,'Praça');
INSERT INTO T_SAK_BAIRRO (cd_bairro,cd_cidade,nm_bairro) VALUES (seq_bairro.nextval,86,'Cachoeira');

