CREATE SEQUENCE seq_proj
As int
start with 1
Increment by 1 ;


INSERT INTO
T_SAK_PROJETO (CD_PROJETO,NM_PROJETO,VL_BUDGET_PROJETO,DT_INICIO,DT_TERMINO) 
VALUES (seq_proj.nextval,'IMPLEMENTAÇÃO INFRAESTRUTURA CLOUD AZURE',2000,TO_DATE(20-05-15),NULL);

INSERT INTO 
T_SAK_PROJETO (CD_PROJETO,NM_PROJETO,VL_BUDGET_PROJETO,DT_INICIO,DT_TERMINO) 
VALUES (seq_proj.nextval,'APP MOBILE SAKSPILDAP',5000,TO_DATE(19-04-27),NULL);

INSERT INTO
T_SAK_PROJETO (CD_PROJETO,NM_PROJETO,VL_BUDGET_PROJETO,DT_INICIO,DT_TERMINO) 
VALUES (seq_proj.nextval,'PORTAL SAKSPILDAP',4500,TO_DATE(20-01-20),NULL);
