INSERT INTO 
T_SAK_PROJETO (CD_PROJETO,NM_PROJETO,VL_BUDGET_PROJETO,DT_INICIO,DT_TERMINO) 
VALUES (seq_proj.nextval,'API FAST ACCESS',2500,TO_DATE('05/10/2020','DD/MM/YYYY'),TO_DATE('30/10/2020','DD/MM/YYYY'));

INSERT INTO
T_SAK_PROJETO (CD_PROJETO,NM_PROJETO,VL_BUDGET_PROJETO,DT_INICIO,DT_TERMINO) 
VALUES (seq_proj.nextval,'CHATBOT',4500,TO_DATE('26/09/2019','DD/MM/YYYY'),TO_DATE('01/12/2020','DD/MM/YYYY'));
