INSERT INTO
T_SAK_PROJETO (CD_PROJETO,NM_PROJETO,VL_BUDGET_PROJETO,DT_INICIO,DT_TERMINO) 
VALUES (seq_proj.nextval,'IMPLEMENTAÇÃO INFRAESTRUTURA CLOUD AZURE',2000,TO_DATE('20/01/2020','DD/MM/YYYY'),NULL);

INSERT INTO 
T_SAK_PROJETO (CD_PROJETO,NM_PROJETO,VL_BUDGET_PROJETO,DT_INICIO,DT_TERMINO) 
VALUES (seq_proj.nextval,'APP MOBILE SAKSPILDAP',5000,TO_DATE('15/05/2020','DD/MM/YYYY'),NULL);

INSERT INTO
T_SAK_PROJETO (CD_PROJETO,NM_PROJETO,VL_BUDGET_PROJETO,DT_INICIO,DT_TERMINO) 
VALUES (seq_proj.nextval,'PORTAL SAKSPILDAP',4500,TO_DATE('13/07/2019','DD/MM/YYYY'),NULL);
