INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (1,seq_end_func.nextval,2631,1,NULL,44);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (1,seq_end_func.nextval,2667,3,NULL,16);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (2,seq_end_func.nextval,2345,1,'APT 42 BLOCO A',88);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (2,seq_end_func.nextval,2415,1,NULL,73);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (3,seq_end_func.nextval,2445,1,'APT 15 BLOCO C',55);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (3,seq_end_func.nextval,2674,1,NULL,65);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (4,seq_end_func.nextval,2619,1,NULL,37);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (4,seq_end_func.nextval,2654,1,NULL,39);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (5,seq_end_func.nextval,1346,1,'APT 23 BLOCO B',39);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (5,seq_end_func.nextval,2173,1,'APT 15',73);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (6,seq_end_func.nextval,1178,1,NULL,131);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (6,seq_end_func.nextval,1179,1,NULL,654);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (7,seq_end_func.nextval,705,1,NULL,164);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (7,seq_end_func.nextval,708,2,NULL,210);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (8,seq_end_func.nextval,854,1,NULL,1);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (8,seq_end_func.nextval,854,1,NULL,2);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (9,seq_end_func.nextval,953,3,NULL,14);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (9,seq_end_func.nextval,952,1,NULL,59);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (10,seq_end_func.nextval,1152,1,NULL,197);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (10,seq_end_func.nextval,1153,1,NULL,1);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (11,seq_end_func.nextval,1196,3,NULL,751);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (11,seq_end_func.nextval,1197,1,NULL,729);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (12,seq_end_func.nextval,1292,2,NULL,905);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (12,seq_end_func.nextval,1297,1,NULL,282);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (13,seq_end_func.nextval,1501,1,'CASA 1',11);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (13,seq_end_func.nextval,1682,1,NULL,106);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (14,seq_end_func.nextval,1326,1,NULL,56);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (14,seq_end_func.nextval,1497,1,NULL,99);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (15,seq_end_func.nextval,1999,1,NULL,7800);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (15,seq_end_func.nextval,1725,1,NULL,522);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (16,seq_end_func.nextval,1633,1,'APTO 8A',8);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (16,seq_end_func.nextval,1420,1,'APTO 56',566);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (17,seq_end_func.nextval,1722,1,NULL,117);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (17,seq_end_func.nextval,1346,1,NULL,954);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (18,seq_end_func.nextval,1249,1,NULL,164);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (18,seq_end_func.nextval,1982,1,'CASA 3',300);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (19,seq_end_func.nextval,2526,1,'CASA 3',285);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (19,seq_end_func.nextval,2527,1,'CASA 4',489);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (20,seq_end_func.nextval,2599,1,'CASA 1',64);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (20,seq_end_func.nextval,2600,1,'CASA 2',222);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (21,seq_end_func.nextval,2561,1,'APTO 83',444);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (21,seq_end_func.nextval,2562,1,'APTO 32',322);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (22,seq_end_func.nextval,2569,1,'CASA 2',211);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (22,seq_end_func.nextval,2570,1,'APTO 21',199);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (23,seq_end_func.nextval,2588,1,'CASA 3',322);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (23,seq_end_func.nextval,2589,1,'CASA 5',521);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (24,seq_end_func.nextval,2584,1,'APTO 91',910);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (24,seq_end_func.nextval,2585,1,'CASA 2',234);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (25,seq_end_func.nextval,2598,1,'APTO 81',810);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (25,seq_end_func.nextval,2599,1,'APTO 82',822);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (26,seq_end_func.nextval,2601,1,'1',476);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (26,seq_end_func.nextval,2602,3,'NULL',299);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (27,seq_end_func.nextval,2603,1,'NULL',666);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (27,seq_end_func.nextval,2604,1,'CASA 3',539);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (28,seq_end_func.nextval,2605,1,'NULL',198);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (28,seq_end_func.nextval,2606,1,'NULL',239);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (29,seq_end_func.nextval,2607,1,'NULL',584);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (29,seq_end_func.nextval,2608,1,'NULL',78);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (30,seq_end_func.nextval,2609,1,'NULL',499);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (30,seq_end_func.nextval,2610,1,'NULL',159);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (31,seq_end_func.nextval,2611,1,'NULL',6);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (CD_FUNC,CD_END_FUNC,CD_END_CORREIO,CD_TIPO_ENDERECO,DS_COMPLEMENTO,NR_LOGRADOURO) VALUES (31,seq_end_func.nextval,2612,1,'NULL',481);
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (32,seq_end_func.nextval,3242,1,NULL,508);															
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (32,seq_end_func.nextval,3243,1,NULL,677);															
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (33,seq_end_func.nextval,3244,1,NULL,56);														
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (33,seq_end_func.nextval,3245,1,NULL,340);															
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (34,seq_end_func.nextval,3246,1,NULL,843);															
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (34,seq_end_func.nextval,3247,1,NULL,700);															
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (35,seq_end_func.nextval,3248,1,NULL,45);															
INSERT INTO T_SAK_FUNCIONARIO_ENDERECO (cd_func,cd_end_func,cd_end_correio,cd_tipo_endereco,ds_complemento,nr_logradouro) VALUES (35,seq_end_func.nextval,3249,1,NULL,890);															