CREATE SEQUENCE seq_estado
As int
start with 1
Increment by 1 ;


INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (1,'ACRE','AC');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (2,'ALAGOAS','AL');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (3,'AMAPÁ','AP');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (4,'AMAZONAS','AM');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (5,'BAHIA','BA');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (6,'CEARÁ','CE');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (7,'ESPÍRITO SANTO','ES');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (8,'GOIÁS','GO');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (9,'MARANHÃO','MA');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (10,'MATO GROSSO','MT');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (11,'MATO GROSSO DO SUL','MS');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (12,'MINAS GERAIS','MG');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (13,'PARÁ','PA');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (14,'PARAÍBA','PB');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (15,'PARANÁ','PR');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (16,'PERNAMBUCO','PE');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (17,'PIAUÍ','PI');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (18,'RIO DE JANEIRO','RJ');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (19,'RIO GRANDE DO NORTE','RN');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (20,'RIO GRANDE DO SUL','RS');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (21,'RONDÔNIA','RO');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (22,'RORAIMA','RR');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (23,'SANTA CATARINA','SC');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (24,'SÃO PAULO','SP');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (25,'SERGIPE','SE');
INSERT INTO T_SAK_ESTADO (CD_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (26,'TOCANTINS','TO');
