INSERT INTO T_SAK_DEPENDENTE (cd_func,id_dependente,nm_dependente,dt_nascimento,st_dependente) VALUES (2,1,'MARIANA SOUZA',TO_DATE('25/06/2000','DD/MM/YYYY'),'ATIVO')
INSERT INTO T_SAK_DEPENDENTE (cd_func,id_dependente,nm_dependente,dt_nascimento,st_dependente) VALUES	(3,2,'RAFAELA DIAS',TO_DATE('18/12/1974','DD/MM/YYYY'),'ATIVO')
INSERT INTO T_SAK_DEPENDENTE (cd_func,id_dependente,nm_dependente,dt_nascimento,st_dependente) VALUES	(4,3,'LUCAS VALÉRIO',TO_DATE('22/07/1991','DD/MM/YYYY'),'ATIVO')
INSERT INTO T_SAK_DEPENDENTE (cd_func,id_dependente,nm_dependente,dt_nascimento,st_dependente) VALUES	(5,4,'CARLA OLIVEIRA',TO_DATE('30/09/1985','DD/MM/YYYY'),'ATIVO')
INSERT INTO T_SAK_DEPENDENTE (cd_func,id_dependente,nm_dependente,dt_nascimento,st_dependente) VALUES	(6,5,'JAQUELINE NUNES',TO_DATE('10/03/1980','DD/MM/YYYY'),'ATIVO')
INSERT INTO T_SAK_DEPENDENTE (cd_func,id_dependente,nm_dependente,dt_nascimento,st_dependente) VALUES	(7,6,'WILTON SANTOS',TO_DATE('03/02/1989','DD/MM/YYYY'),'ATIVO')
INSERT INTO T_SAK_DEPENDENTE (cd_func,id_dependente,nm_dependente,dt_nascimento,st_dependente) VALUES	(8,7,'MICHELE DO SANTOS',TO_DATE('28/10/1987','DD/MM/YYYY'),'ATIVO')
INSERT INTO T_SAK_DEPENDENTE (cd_func,id_dependente,nm_dependente,dt_nascimento,st_dependente) VALUES	(9,8,'DANIELA SILVA',TO_DATE('26/03/1988','DD/MM/YYYY'),'ATIVO')
INSERT INTO T_SAK_DEPENDENTE (cd_func,id_dependente,nm_dependente,dt_nascimento,st_dependente) VALUES	(10,9,'ZACARIAS OLIVEIRA',TO_DATE('07/11/1970','DD/MM/YYYY'),'ATIVO')
