INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,1,'Rio Branco');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,1,'Acrelândia');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,1,'Porto Acre');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,1,'Tarauacá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,1,'Rodrigues Alves');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,1,'Xapuri');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,1,'Capixaba');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,1,'Bujari');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,1,'Brasileia');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,1,'Assis Brasil');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,2,'Maceió');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,2,'Batalha');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,2,'Belém');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,2,'Cajueiro');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,2,'Canapi');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,2,'Carneiros');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,2,'Coruripe');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,2,'Flexeiras');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,2,'Igaci');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,2,'Japaratinga');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,3,'Macapá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,3,'Cutias');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,3,'Mazagão');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,3,'Oiapoque');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,3,'Santana');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,3,'Serra do Navio');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,3,'Tartarugalzinho');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,3,'Vitória do Jari');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,3,'Pracuúba');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,3,'Itaubal');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,4,'Manaus');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,4,'Coari');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,4,'Lábrea');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,4,'Maués');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,4,'Borba');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,4,'Careiro');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,4,'Tartarugalzinho');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,4,'Manacapuru');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,4,'Eirunepé');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,4,'Boca do Acre');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,5,'Salvador');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,5,'Feira de Santana');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,5,'Vitória da Conquista');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,5,'Camaçari');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,5,'Juazeiro');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,5,'Itabuna');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,5,'Lauro de Freitas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,5,'Ilhéus');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,5,'Jequié');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,5,'Teixeira de Freitas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,6,'Fortaleza');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,6,'Caucaia');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,6,'Juazeiro do Norte');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,6,'Maracanaú');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,6,'Sobral');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,6,'Itapipoca');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,6,'Maranguape');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,6,'Iguatu');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,6,'Quixadá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,6,'Crato');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,7,'Vitória');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,7,'Vila Velha');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,7,'Cariacica');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,7,'Cachoeiro de Itapemirim');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,7,'Linhares');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,7,'São Mateus');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,7,'Guarapari');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,7,'Colatina');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,7,'Aracruz');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,7,'Viana');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,8,'Goiânia');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,8,'Jataí');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,8,'Mineiros');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,8,'Aparecida de Goiânia');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,8,'Rio Verde');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,8,'Água Limpa');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,8,'Anápolis');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,8,'Luziânia');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,8,'Trindade');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,8,'Formosa');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,9,'São Luís');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,9,'Imperatriz');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,9,'Timon');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,9,'Santa Inês');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,9,'Caxias');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,9,'Codó');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,9,'Açailândia');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,9,'Paço do Lumiar');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,9,'Pinheiro');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,9,'Chapadinha');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,10,'Cuiabá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,10,'Várzea Grande');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,10,'Rondonópolis');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,10,'Sinop');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,10,'Tangará da Serra');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,10,'Cáceres');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,10,'Barra do Garças');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,10,'Lucas do Rio Verde');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,10,'Juína');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,10,'Colniza');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,11,'Campo Grande');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,11,'Dourados');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,11,'Três Lagoas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,11,'Corumbá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,11,'Ponta Porã');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,11,'Sidrolândia');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,11,'Naviraí');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,11,'Nova Andradina');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,11,'Aquidauana');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,11,'Maracaju');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,12,'Belo Horizonte');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,12,'Uberlândia');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,12,'Contagem');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,12,'Juiz de Fora');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,12,'Betim');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,12,'Uberaba');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,12,'Ipatinga');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,12,'Divinópolis');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,12,'Santa Luzia');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,12,'Ibirité');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,13,'Belém');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,13,'Ananindeua');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,13,'Santarém');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,13,'Marabá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,13,'Parauapebas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,13,'Bragança');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,13,'São Félix do Xingu');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,13,'Barcarena');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,13,'Tucuruí');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,13,'Paragominas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,14,'João Pessoa');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,14,'Campina Grande');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,14,'Patos');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,14,'Santa Rita');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,14,'Bayeux');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,14,'Sousa');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,14,'Cabedelo');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,14,'Cajazeiras');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,14,'Guarabira');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,14,'Sapé');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,15,'Curitiba');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,15,'Araucária');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,15,'Paranaguá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,15,'Guarapuava');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,15,'Colombo');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,15,'Cascavel');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,15,'Ponta Grossa');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,15,'Maringá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,15,'Foz do Iguaçú');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,15,'Londrina');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,16,'Recife');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,16,'Olinda');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,16,'Caruaru');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,16,'Petrolina');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,16,'Paulista');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,16,'Cabo de Santo Agostinho');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,16,'Camaragibe');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,16,'Garanhuns');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,16,'Vitória de Santo Antão');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,16,'Jaboatão dos Guararapes');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,17,'Teresina');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,17,'Esperantina');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,17,'Altos');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,17,'União');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,17,'Campo maior');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,17,'Barras');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,17,'Floriano');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,17,'Piripiri');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,17,'Picos');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,17,'Parnaíba');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,18,'Rio de Janeiro');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,18,'São Gonçalo');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,18,'Duque de Caxias');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,18,'Nova Iguaçu');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,18,'Niterói');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,18,'Belford Roxo');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,18,'Campos dos Goytacazes');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,18,'São João de Meriti');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,18,'Petrópolis');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,18,'Angra dos Reis');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,19,'Natal');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,19,'Mossoró');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,19,'Parnamirim');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,19,'Macaíba');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,19,'São Gonçalo do Amarante');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,19,'Caicó');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,19,'Currais Novos');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,19,'Nova Cruz');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,19,'Santa Cruz');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,19,'Apodi');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,20,'Porto Alegre');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,20,'Caxias do Sul');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,20,'Canoas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,20,'Pelotas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,20,'Santa Maria');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,20,'Gravataí');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,20,'Novo Hamburgo');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,20,'Passo Fundo');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,20,'Alvorada');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,20,'Erechim');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,21,'Porto Velho');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,21,'Ji-Paraná');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,21,'Ariquemes');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,21,'Vilhena');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,21,'Cacoal');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,21,'Rolim de Moura');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,21,'Jaru');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,21,'Guajará-Mirim');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,21,'Pimenta Bueno');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,21,'Buritis');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,22,'Boa Vista');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,22,'Rorainópolis');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,22,'Caracaraí');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,22,'Cantá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,22,'Mucajaí');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,22,'Pacaraima');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,22,'Alto Alegre');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,22,'Amajari');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,22,'Bonfim');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,22,'Iracema');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,23,'Florianópolis');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,23,'Palhoça');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,23,'São José');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,23,'Alfredo Wagner');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,23,'Águas Mornas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,23,'São Bonifácio');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,23,'Canelinha');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,23,'Canoinhas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,23,'Major Vieira');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,23,'Papanduva');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,24,'São Paulo');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,24,'Osasco');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,24,'Praia Grande');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,24,'Santos');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,24,'Guarujá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,24,'Campinas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,24,'Guarulhos');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,24,'Diadema');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,24,'Mauá');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,24,'Itapevi');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,25,'Aracaju');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,25,'Areia Branca');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,25,'Macambira');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,25,'São Domingos');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,25,'Riachão do Dantas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,25,'Malhada dos Bois');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,25,'Muribeca');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,25,'Poço Verde');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,25,'Estância');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,25,'Siriri');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,26,'Palmas');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,26,'Goianorte');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,26,'Guaraí');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,26,'Miranorte');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,26,'Monte Santo do Tocantins');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,26,'Pium');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,26,'Taguatinga');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,26,'Lizarda');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,26,'Silvanópolis');
INSERT INTO T_SAK_CIDADE (cd_cidade,cd_estado,nm_cidade) VALUES (seq_cidade.nextval,26,'Campos Lindos');
